# Generated by Django 3.2.9 on 2021-11-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('scene', models.CharField(max_length=80)),
                ('notes', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('camera', models.ForeignKey(help_text='The camera that has taken the picture.', on_delete=django.db.models.deletion.PROTECT, to='Core.camera')),
            ],
        ),
    ]
