# Generated by Django 4.0.1 on 2022-01-19 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_alter_camera_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='pwd',
            field=models.CharField(default='insecure --> change', help_text='The password that the camera must use in the picture upload form.', max_length=80, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Who can see this camera's pictures?", to=settings.AUTH_USER_MODEL),
        ),
    ]
