# Generated by Django 4.0.1 on 2022-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_camera_pwd_camera_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(help_text='The time at which the camera took the picture.', null=True),
        ),
    ]
