# Generated by Django 4.0.1 on 2022-01-30 12:27

import datetime
from backports.zoneinfo import ZoneInfo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_picture_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0, tzinfo=ZoneInfo('Europe/Berlin')), help_text='The time at which the camera took the picture.'),
            preserve_default=False,
        ),
    ]
