# Generated by Django 4.0.2 on 2022-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_picture_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
