# Generated by Django 4.0.2 on 2022-02-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_picture_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='filename',
        ),
    ]
